### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by RienduPre** [Samfox2/homebridge-doorbell#4]
Hi,

I followed your procedure, but nothing happens when I ring my DoorBird.

The DoorBird camera is visible in the Home App and I have a Doorbell accesoire, which states not supported

Any help is appreciated.

Thanks,
Rien

**Comment by brownad** [comment]
You need to have the camera configured too using the ffmpeg plugin, have both accessories in the same room. When you restart homebridge it will fire off the event to take a screenshot and push to iOS.


The trigger on pressing anything does not exist. That needs wiring up the doorbird api. Something i want to do but have no time

**Comment by RienduPre** [comment]
I have the Doorbird camera using ffmpeg running and both are in the same room. Nothing happens when I restart the homebridge. What am I missing?

**Comment by RienduPre** [comment]
![img_1934](https://cloud.githubusercontent.com/assets/9009949/22173444/5cd2f36a-dfc3-11e6-9150-c18c478d1fed.jpg)

**Comment by brownad** [comment]
Share your doorbell config Json please

**Comment by RienduPre** [comment]
Here you go

{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:32",
    "port": 51826,
    "pin": "031-45-134"
  },
  "platforms": [
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Front Door",
      "videoConfig": {
      	"source": "-re -i http://192.168.0.198:80/bha-api/video.cgi?http-user=user&http-password=pw",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 6
      }
    },
    {
      "name": "Oprit",
      "videoConfig": {
      	"source": "-re -i rtsp://user:pw!@192.168.0.197/11",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 20
      }
    }
  ]
},
{
        "platform": "Doorbell",
        "doorbells": [
        {
            "name": "Front Door"
        }
        ]
},

**Comment by ygageot** [comment]
In my case I developed a Doorbell support in the Homewizard Homebridge plugin.
Until 11/1/2017 it was working and in Home app I had smart notifications when button pushed.
Since this date the Home app show the accessory as "non supported".
When it was working, I used it with a doorbell button alone without HomeKit camera.

I discovered in Homekit Accessory Simulator that it was not possible to simulate an accessory with only Doorbell service but we had only "Video doorbell" a compound with IPcamera+CameraControl+Microphone+Speaker+Doorbell+MotionSensor by default...
I think that Apple made changes recently preparing the new iOs version.

I am interested by any experience.

**Comment by brownad** [comment]
What does the compound look like? Didn't think it was possible to have all of that in one.  Is it possible to stream doorbird audio?

**Comment by ygageot** [comment]
![capture d ecran 4](https://cloud.githubusercontent.com/assets/3415324/22302389/e700546a-e32e-11e6-9148-f125da9a3fbe.png)
![capture d ecran 3](https://cloud.githubusercontent.com/assets/3415324/22302399/f403e82a-e32e-11e6-810e-02969fc77e1a.png)
In Homekit Accessory Simulator when you create a Video Doorbell, you have automatically a Microphone and a Speaker as Linked Service by default but you can delete it... You can't delete the IP camera.

**Comment by brownad** [comment]
Never seen that before but very encouraging . Does it help to bring together the doorbird experience? 

What doesn't work when this is used?  Or is it just a simulator nothing more?

**Comment by brownad** [comment]
Does that mean a full video doorbell can be created?

**Comment by brownad** [comment]
@ygageot

I took a stab at making this work for the doorbird
https://github.com/brownad/homebridge-doorbird

I'm not sure if calling the setValue is corrrect or this just no longer works. Can you help?

**Comment by brownad** [comment]
Actually it's working for me now 😀

**Comment by RienduPre** [comment]
Could you share some pictures?

I see this in the logging when I ring the Doorbird
<img width="462" alt="2017-01-28_1047" src="https://cloud.githubusercontent.com/assets/9009949/22396323/fd91aa48-e555-11e6-91f1-11f5d837a41b.png">

But I don't see any device in my phone except the non supported device

**Comment by brownad** [comment]
Hi

It's firing off initially on first press after a restart, but I think it's random if it takes a picture at the moment so far 75% worked. Then I think I need to reset state, not sure how to do this correctly yet. Have asked a question on it.

**Comment by brownad** [comment]
I've made a few more changes to reset state. It is a bit rough but is pushing through to iOS 

However there is a limitation with the device it is received on, only one of three devices (one is an invite to HomeKit). So that's a bit of a limitation. It's not got the same experience as a smoke alarm notification unfortunately unless someone knows how to push this to all devices?

**Comment by brownad** [comment]
You need to remove the old plugin and add this one to the same room as your camera. If you don't remove it cleanly reference it with the full name eg read the log output if it conflicts it does say there are two doorbell platforms.

**Comment by RienduPre** [comment]
Ok maybe I am confused (from the beginning on)

What is the functionality of this plugin ? What does it look like on your iOS device and what are the current limitations.
And what is the correct order to install?
It never worked for me and I have over 90 devices in Homekit via de HomeBridge and I don't like to start over again every time.
So before I go on testing I like to know if it's worth it.

Thanks,
Rien

**Comment by brownad** [comment]
The 'plugin' allows for the simulated doorbell.

You add it to the same room as your camera in this case doorbird. It shows up as not supported that is known already. It does nothing if you press the button in the app.

If someone presses the doorbell on the doorbird it takes a screenshot and pushes it to your iOS device lock screen. So on your iOS have you enabled notifications to appear?  Once you get them you can slide it across and go straight to the camera feed.

Think of it like the doorbird notification only with a very small image added.

It does need more changes and will be replaced when video doorbell support comes in but it's running 'ok' for me.  If you want to use instead of Samfox plugin you need to remove his one cleanly or reference it fully as it says in the start up log

**Comment by RienduPre** [comment]
Hi,

Thanks for your clarification.
I removed all accesoires from the Home App and installed and configured the DoorBird plugin. Add the accessories again and put the Camera and the 'unsupported' accessoire in the same room (see picture)
I see in the log that the doorbell is pressed, but on my iphone there is no notification (excepted the one form the doorbird app itself)

![img_3145](https://cloud.githubusercontent.com/assets/9009949/22430025/00b798be-e70d-11e6-9e7d-b41ba15cd790.JPG)

**Comment by brownad** [comment]
Ok

And I assume you have HomeKit assigned to your iCloud account directly?

I've got a problem where only one of my three devices (one is using as an invite to HomeKit) and they never receive updates. Only the 'owning' phone gets them.  I asked a question about this but no response yet.

**Comment by RienduPre** [comment]
Yes, HomeKit is on iCloud and several devices (1 iphone and several iPad, Apple TV's) are using the same acoount.
What do you mean by 'owning' phone? The one where I configured the accessoires on initially ?

**Comment by brownad** [comment]
I am not sure then.

**Comment by brownad** [comment]
Have you tested it without other sensors in the room?  I still haven't got my head around why only one device gets the notification

My setup is just :

Porch light
Doorbird doorbell
Porch camera

**Comment by brownad** [comment]
I think this is an issue with latest iOS too, I've reinstalled and looked at homebridge debug and nothing happening, same with my version. Am following the upcoming updates for a video doorbell change to make the switch programmable.

Does this work for you on latest iOS samfox2? After a reinstall?

**Comment by Samfox2** [comment]
Please have a look at homebridge-videodoorbell
